# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.13
      uses: actions/setup-java@v1
      with:
        java-version: 1.13
    - name: Download RTCToolbox
      run: mvn validate -B -Peclipse,tests,exp,mpa
    - name: Check lib
      run: ls lib
    - name: Compile with Maven
      run: mvn compile -B -Peclipse,tests,exp,mpa
    - name: Check lib
      run: ls lib
    - name: Test with Maven
      run: mvn test -B -Peclipse,tests,exp,mpa
    - name: Check lib
      run: ls lib

  build:
    runs-on: ubuntu-latest
    needs: compile
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.13
      uses: actions/setup-java@v1
      with:
        java-version: 1.13
    - name: Build with Maven
      run: mvn -B -Peclipse,tests,exp,mpa package --file pom.xml
